name: Upload Python Package

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.release.repository }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: deps
        run: python -m pip install -U build
      
      - name: build
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
